export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_FAILURE = "SET_USER_FAILURE";
export const CLEAR_SET_USER_ERROR = "CLEAR_SET_USER_ERROR";

export const ADD_BOOKMARK_SUCCESS = "ADD_BOOKMARK_SUCCESS";
export const ADD_BOOKMARK_FAILURE = "ADD_BOOKMARK_FAILURE";
export const CLEAR_ADD_BOOKMARK_ERROR = "CLEAR_ADD_BOOKMARK_ERROR";
